#see https://github.com/pypa/setuptools_scm/
# pyproject.toml
[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.0"]

# make sure this file is in .gitignore
[tool.setuptools_scm]
write_to = "src/quiz_mill/_version.py"